/**
 * Chunk = the base unit of a course (spec §4.1). Every chunk is authored /
 * template-generated by hand and comes with an entry/exit contract so the
 * assembler can snap them together deterministically.
 *
 * Coordinate convention (shared by sim + renderer):
 *   - Units are TILES. x grows to the right, y grows DOWNWARD (Phaser-style).
 *   - A platform rect {x,y,w,h} covers tiles [x, x+w) horizontally and
 *     [y, y+h) vertically. Its walkable TOP surface is the line y.
 *   - entryY / exitY are the tile-y of the floor surface at the left/right
 *     edge. A chunk B may follow A iff |A.exitY - B.entryY| <= 1.
 */

export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

/** A platform that oscillates deterministically as a function of frame. */
export interface Mover extends Rect {
  /** Axis of travel. */
  axis: 'x' | 'y';
  /** Peak displacement in tiles from the rest position. */
  amp: number;
  /** Oscillation period in simulation frames. */
  period: number;
  /** Phase offset in frames (keeps determinism, adds variety). */
  phase?: number;
}

export type HazardType = 'spike' | 'saw';

export interface Hazard {
  type: HazardType;
  x: number;
  y: number;
  /** Saw blades sweep; spikes are static. */
  axis?: 'x' | 'y';
  amp?: number;
  period?: number;
  phase?: number;
}

export interface TrapSlot {
  x: number;
  y: number;
}

export interface Point {
  x: number;
  y: number;
}

export interface Chunk {
  id: string;
  widthTiles: number;
  heightTiles: number;
  entryY: number;
  exitY: number;
  /** 1..5 authored difficulty. */
  difficulty: number;
  tags: string[];
  platforms: Rect[];
  movers?: Mover[];
  hazards?: Hazard[];
  trapSlots?: TrapSlot[];
  /** Optional mid-chunk checkpoint (in-chunk tile coords). */
  checkpoint?: Point;
}
